[build]
builder = "NIXPACKS"
nixpacksProvider = "node"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npx serve dist -s -l tcp://0.0.0.0:${PORT:-3000}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
